apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-gnb-du.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oai-gnb-du.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-gnb-du.selectorLabels" . | nindent 8 }}
        app: 5grf-sim
    {{- if .Values.multus.create }}
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [{
                 "name": "{{ .Chart.Name }}-net1",
                 "default-route": ["{{ .Values.multus.defaultGateway }}"]
          },
          {
                 "name": "{{ .Chart.Name }}-net2"
          }]
    {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
      containers:
      - name: gnbdu
        image: "{{ .Values.nfimage.repository }}:{{ .Values.nfimage.version }}"
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.service.s1uPort }}
          name: s1u
          protocol: UDP
        - containerPort: {{ .Values.service.s1cPort }}
          name: s1c
          protocol: UDP
        - containerPort: {{ .Values.service.x2cPort }}
          name: x2c
          protocol: UDP
        {{- if .Values.start.gnbdu}}
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: timeZone
          - name: RFSIMULATOR
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: rfSimulator
          - name: USE_SA_TDD_CU
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: usesatddcu
          - name: GNB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gnbduName
          - name: MCC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mcc
          - name: MNC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mnc
          - name: MNC_LENGTH
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mncLength
          - name: TAC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac
          - name: NSSAI_SST
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nssaiSst
          - name: NSSAI_SD0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nssaiSd0
          - name: NSSAI_SD1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nssaiSd1
          - name: AMF_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: amfIpAddress
          - name: GNB_NGA_IF_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gnbNgaIfName
          - name: GNB_NGA_IP_ADDRESS
            {{- if eq .Values.config.gnbNgaIpAddress "status.podIP" }}
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
            {{- else}}
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gnbNgaIpAddress
            {{- end}}
          - name: GNB_NGU_IF_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gnbNguIfName
          - name: GNB_NGU_IP_ADDRESS
            {{- if eq .Values.config.gnbNguIpAddress "status.podIP" }}
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
            {{- else}}
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gnbNguIpAddress
            {{- end}}
          - name: F1_IF_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: f1IfName
          - name: F1_DU_IP_ADDRESS
            {{- if eq .Values.config.f1duIpAddress "status.podIP" }}
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
            {{- else}}
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: f1duIpAddress
            {{- end}}
          - name: F1_CU_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: f1cuIpAddress
          - name: F1_CU_D_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: f1cuPort
          - name: F1_DU_D_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: f1duPort
          - name: USE_ADDITIONAL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: useAdditionalOptions
      - name: tcpdump
        image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /tmp/oai-gnb-du_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        volumeMounts:
        {{- if .Values.persistence.sharedvolume}}
        - mountPath: "/pcap"
          name: cn5g-pv
        {{- end}}
      volumes:
      {{- if .Values.persistence.sharedvolume}}
      - name: cn5g-pv
        persistenceVolumeClaim:
          claimName: cn5g-pvc
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}


